<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-03T11:13:35 IST" name="Suite" finished-at="2022-09-03T11:14:31 IST" duration-ms="56642">
    <groups>
    </groups>
    <test started-at="2022-09-03T11:13:35 IST" name="Test" finished-at="2022-09-03T11:14:31 IST" duration-ms="56642">
      <class name="TestCases.VerifyLoginTestCase">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.VerifyLoginTestCase@dbf57b3]" started-at="2022-09-03T11:13:35 IST" name="launchBrowser" finished-at="2022-09-03T11:13:43 IST" duration-ms="8313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="login()[pri:0, instance:TestCases.VerifyLoginTestCase@dbf57b3]" started-at="2022-09-03T11:13:43 IST" name="login" finished-at="2022-09-03T11:13:44 IST" duration-ms="861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.VerifyLoginTestCase@dbf57b3]" started-at="2022-09-03T11:13:44 IST" name="tearDown" finished-at="2022-09-03T11:13:50 IST" duration-ms="6057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.VerifyLoginTestCase -->
      <class name="TestCases.VerifySignUpTestCase">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.VerifySignUpTestCase@37afeb11]" started-at="2022-09-03T11:13:50 IST" name="launchBrowser" finished-at="2022-09-03T11:13:57 IST" duration-ms="6621" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="SignUp()[pri:0, instance:TestCases.VerifySignUpTestCase@37afeb11]" started-at="2022-09-03T11:13:57 IST" name="SignUp" finished-at="2022-09-03T11:14:25 IST" duration-ms="27932" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Free CRM Trial: Salesforce 30-Day Trial- Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Free CRM Trial: Salesforce 30-Day Trial- Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.CommonUtilities.handleAssertions(CommonUtilities.java:24)
at TestCases.VerifySignUpTestCase.SignUp(VerifySignUpTestCase.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.VerifySignUpTestCase@37afeb11]" started-at="2022-09-03T11:14:25 IST" name="tearDown" finished-at="2022-09-03T11:14:31 IST" duration-ms="6788" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.VerifySignUpTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
